default_language_version:
  python: "3.12"
default_stages: [pre-commit]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-json
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: detect-private-key
      - id: check-ast
      - id: mixed-line-ending

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.4.0
    hooks:
      - id: pyupgrade
        files: ^backend/

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.0.0-alpha.9-for-vscode"
    hooks:
      - id: prettier
        files: ^backend/
        exclude: "backend/app/templates/"
        args: ["--tab-width", "2"]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.4
    hooks:
      - id: ruff
        args: [ --config=backend/pyproject.toml, --fix ]
        files: ^backend/
      - id: ruff-format
        args: [ --config=backend/pyproject.toml ]
        files: ^backend/

  - repo: https://github.com/pycqa/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        files: ^backend/
        exclude: "test_*"
        args: ["-iii", "-ll", "-s=B308,B703"]
